### PR TITLE
Add more descriptive text to the README

### PR DESCRIPTION
**Pull request by cbracco**
Greetings,

As a part of the [Modern Developer](https://learn.modern-developer.com/) programming academy, we were asked to add some information to the README of a popular repository on GitHub, and submit our changes as a pull request. @DevonAero & I added some further info to the README based on your documentation. If you decide you want to add it to the repository, that would be awesome. Please have a look and consider this small addition. :v:  Cheers!

### CODE REVIEW

**Comment by zackbloom** [comment]
Nice job!

**Comment by geekjuice** [comment]
whoa :clap: :tada:

**Comment by cbracco** [comment]
Awesome! Thanks for accepting our request :smiley: :confetti_ball: :confetti_ball:

**Comment by DevonAero** [comment]
Thanks guys, lots of fun working on it! And great project! :)

**Comment by timmfin** [comment]
:dancers: :memo:

**Pull request merged**
