### PR TITLE
Opear 12.16 doesn't support translateZ

### PR DESCRIPTION
**Pull request by Katochimoto**
General check the possibility of using translateZ.

### CODE REVIEW

**Comment by cvrebert** [comment]
@Katochimoto This has unresolved merge conflicts.

**Comment by TrevorBurnham** [comment]
What are the consequences of adding `translateZ(0)` in a browser that doesn't support it?

**Comment by TrevorBurnham** [comment]
I don't see how adding `translateZ(0)` in a browser that doesn't support it can be harmful. If I'm mistaken, please elaborate.

**Comment by DiscoNova** [comment]
In theory, adding any unrecognised declarations into CSS is supposed to be disregarded by the browser. Therefore there should be no ill effects. However, the pull request does specifically mention IE9 "choking" if 3D-transformation is provided, but frankly I've never witnessed this - I've seen it mentioned elsewhere, though, so it is possible that under some circumstances it really does happen.

Personally, I've always felt that using a null Z-axis transform in an attempt to "force" browser to use GPU-acceleration is a bit of a hack that can easily misfire. In my opinion the whole trick should not be used as a "catch-all" attempt to boost performance and should instead be left for the developers to decide when (and if) it should take place.

**Pull request closed without merging**
