### PR TITLE
Fix: server rendering by checking document and window object are defined

### PR DESCRIPTION
**Pull request by sujaykathrotia**
Server side rendering was not working as the JavaScript threw the Reference Error.
Check this issue: https://github.com/Hacker0x01/react-datepicker/issues/179

### CODE REVIEW

**Comment by bruno12mota** [comment]
+1 for this

**Comment by ivarconr** [comment]
+1

**Comment by geekjuice** [comment]
Should `Tether` even execute for server-side rendering? If the assumption is that `Tether` shouldn't even execute on the server, would it make sense to just wrap the entire file in a function that checks that `document` and `window` are defined? For example:

```javascript
let Tether;
if (typeof window !== 'undefined' && typeof document !== 'undefined') {

    if (typeof TetherBase === 'undefined') {
      throw new Error('You must include the utils.js file before tether.js');
    }

    const {
      getScrollParent,
      getBounds,
      getOffsetParent,
      extend,
      addClass,
      removeClass,
      updateClasses,
      defer,
      flush,
      getScrollBarSize
    } = TetherBase.Utils;
    
    ...
}
```javascript

**Comment by sujaykathrotia** [comment]
I agree. `Tether` should not execute on the SSR. But then if someone has used object methods like `setOptions`, then it would throw the error. So I think it is better to check for `windows` and `document` only when we use them.

I am fine with either option though.

**Comment by sujaykathrotia** [comment]
An alternative of wrapping the entire file in an if condition, would be to check if `window` is defined at the top of `utils.js`:

```es6
if (typeof window === 'undefined') {
  return;
}
```

Since the output file is wrapped in a factory function, just the `return` statement would do the trick.

**Comment by geekjuice** [comment]
So after dwelling on this for a bit, I think the current implementation in this PR is fine for now since those are the only places where `document` and `window` gets called immediately due to them being inside IIFE. 

Personally, I'm not completely satisfied with the solution, but it is a solution nonetheless and one that does seems to solve the issue well. Ideally, I would like to short-circuit the entire library when `window` and `document ` are `undefined`, but that may require some restructuring of the library.

Thanks again for your patience :+1:

**Comment by sujaykathrotia** [comment]
@geekjuice The last solution I suggested would short-circuit the entire library without restructuring of the library.

**Pull request merged**
