### PR TITLE
Use browserify for building and add some tests

### PR DESCRIPTION
**Pull request by kt3k**
What I did in this PR:
- Introduced browserify for building the module. I think this is better than concatenating for keeping the modularity of the scripts.
  - `standalone: 'Tether'` option in browserify settings makes the bundle `umd`. `dist/js/tether(.min).js` must work as an umd module.
- Added test settings using karma test runner.
  - Added some easy test cases.
- Added .editorconfig

### CODE REVIEW

**Comment by awerlang** [comment]
@TrevorBurnham there's anything we could do to unblock this one? Without it, we are prevented to use `rollup`: https://github.com/rollup/rollup-plugin-babel/issues/87
In time, I don't think it's rollup job to fix the issue, but here on the dist bundle.

Thanks

**Comment by mbaierl** [comment]
Hi,
it would be amazing if this would finally work....

**Comment by nathancahill** [comment]
This should absolutely be merged @Hubspot @TrevorBurnham.

**Comment by balloob** [comment]
I have forked the branch by @kt3k and included a new build on it. As a temporary solution you can refer to Tether like this in your `package.json`:

```json
{
  "dependencies": {
    "tether": "balloob/tether#ef50f750d73e3ea025ced154967a46d760bd404f"
  }
}
```

**Comment by kt3k** [comment]
close this in favor of #359

**Comment by nathancahill** [comment]
@kt3k That's a different project. Issue still exists in this project. Please reopen. There are multiple forks being maintained with your changes until @Hubspot merges this.

**Comment by gthomas-appfolio** [comment]
Yes this should be reopened and merged, fork is being used by [reactstrap](https://github.com/reactstrap/reactstrap) to work around this but would be best to correct here

**Comment by kt3k** [comment]
Oops, thanks for pointing it.

By the way, now I think rollup is better choice for bundling this project because it produces much simpler and smaller bundle than browserify.

**Comment by fantasydr** [comment]
I'm trying to use 'reactstrap' and the issue caused by 'reactstrap-tether' brought me here.

It seems this PR will create a UMD which cannot be consumed by 'browserify'.
The repro is simple. Use an empty project with 'reactstrap-tether':

```json
{
  "dependencies": {  
    "reactstrap-tether": "^1.3.4",  
    "browserify": "^13.0.0"  
  },  
  "name": "bad-require",
  "private": true,
  "scripts": {
    "start": "browserify -d -e test.js",
  },
}
```
The test.js is one line:
```javascript
var tether = require('reactstrap-tether');
```
Run
```
npm run start
```
will generate errors saying
```text
Error: Cannot find module './utils' from .....
```

The webpack might work with this properly. But why break browserify (or did i miss anything) ?

**Comment by zekedroid** [comment]
bump

**Comment by awerlang** [comment]
@zekedroid see https://github.com/HubSpot/tether/blob/master/README.md#rotating_light-project-status-rotating_light

Or use a fork

**Comment by zekedroid** [comment]
Thanks @awerlang! I think I'll try to fix it here first  because the change is needed for `reactstrap-tether` which is needed for `reacstrap`. It would be simplest to make the patch. Unless there's already a fork that is good enough.

**Comment by kt3k** [comment]
Closing for inactivity.

**Pull request closed without merging**
