### PR TITLE
Reposition a center-attached element to left- or right-attached - v2

### PR DESCRIPTION
**Pull request by geekjuice**
#### Status: Testing

Original PR https://github.com/HubSpot/tether/pull/81 ported to new project structure

__Version: `v1.2.0`__

### CODE REVIEW

**Comment by mfrye** [comment]
I could really use this pr as well :+1:

**Comment by jmeridth** [comment]
:+1: have tested in https://github.com/HubSpot/drop/issues/129 and this does exactly what we needed for x-axis auto-repositioning.  Thank you @geekjuice

**Comment by huoxito** [comment]
yeah great stuff @geekjuice thank you and markalfred both for the patch, appreciate it

**Comment by yairEO** [comment]
@geekjuice  -  is this related? http://stackoverflow.com/q/35483837/104380

**Comment by geekjuice** [comment]
Yea, this PR should fix that. On that note, I'll _finally_ merge this in as it seems to be working. Thanks for the friendly reminder about this PR... :disappointed:

**Comment by geekjuice** [comment]
Published on `npm` and `bower` as `1.2.0` :+1:

**Pull request merged**
