### PR TITLE
Remove moot `version` property from bower.json

### PR DESCRIPTION
**Pull request by kkirsche**
Per bower/bower.json-spec@a325da3

### CODE REVIEW

**Comment by geekjuice** [comment]
Thanks for the updates, but it does state it will probably be used in the future and I don't see any issue with keeping it in the file, especially when it still provides useful data.

**Comment by kkirsche** [comment]
To each their own. Any other ones you have I will warn you when the page comes up on bower.io you'll get another pr. No need to comment on them

**Comment by geekjuice** [comment]
Cool :+1: Thanks again for the heads up on this though.

**Comment by kkirsche** [comment]
Also their maintainer says they probably won't ever use it: http://stackoverflow.com/questions/24844901/bowers-bower-json-file-version-property

**Pull request closed without merging**
