### PR TITLE
Adds option to specify body element

### PR DESCRIPTION
**Pull request by pzuraq**
This PR adds a new option, `bodyElement`, which can be used to specify which element the tether's should attach themselves to when moving within the DOM for positioning. This PR is intended to supersede #98 and #192, which were attempts to achieve the same effect. Given that this PR intends to only be a minor version bump, the code from #98 is left intact, but should probably be deprecated and removed in future versions.
### Motivation

New Javascript frameworks like React and Ember oftentimes require more direct control over libraries that were originally intended to be used with just the DOM. In React's case in particular, the VirtualDOM has no `document.body` to speak of and references to it can be problematic. In Ember's case, Fastboot and server side rendering are also done in absence of browser APIs and a body. With Ember animation, things get even more complicated, and I can elaborate on that point if needed.

Tether.js has a single assumption about positioning - that everything is relative to the `document.body`. This allows it to dramatically simplify the logic of positioning. However, consider the following example:

```
<body>
  <div id="ember-app">
    <div style="position: absolute; top: 100px">
      <div id="element-to-tether">
        I'm a tether
      </div>
    </div>
  </div>
<body>
```

In this example, if we were to prevent the tethered element from moving at all, it would be placed 100px out of place, which is not ideal. However, assuming the `ember-app` div has no styles on it at all, then we could attach the tethered element to _that_ div and it would be in the correct place. This is how React and Ember developers would be able to use the new feature to attach tether's within the confines of their applications:

```
const element = $('#element-to-tether')[0];
const bodyElement = $('#ember-app')[0];

const tether = new Tether({ element, bodyElement });
```

It would be up to the developers to ensure that whatever element is considered the `bodyElement` will have the correct characteristics for positioning (same size and position w/ respect to the body).

/cc @jpnelson @nadiam84 @TrevorBurnham @FezVrasta

### CODE REVIEW

**Comment by pzuraq** [comment]
@TrevorBurnham @zackbloom Any word on this? Rebased it, so it's ready to merge. Happy to talk about potential consequences of this API and why it's necessary for frameworks like Ember and React to function properly.

**Comment by madchicken** [comment]
@TrevorBurnham I'd like to see the PR going on master. Any chance to get it merged soon?

**Comment by TrevorBurnham** [comment]
@pzuraq This looks good! 👍  Could you rebase again to update against the latest `master`?

**Comment by pzuraq** [comment]
@TrevorBurnham updated! Thanks for looking over this 😄

**Comment by TrevorBurnham** [comment]
Published as Tether 1.4.0.

**Pull request merged**
