### PR TITLE
add option to disable moving the dom element

### PR DESCRIPTION
**Pull request by piotrpalek**
Hey, I was trying to use tether with Ember.js and it works more or less fine. I encountered a problem while trying to test a component I made with tetherjs. The problem is that tether always moves the element to the body tag and I get why it does so (predictable positioning).
But when I am running the ember test suite it renders the ember application into a special container, and not like normally into the body tag. I need to be able to tell tether to stop moving the element during the tests, where the position isn't really important, because it breaks my app when it tries to move the element to the body tag.

As far as I am aware there is one more place where tether moves the element to the body tag, but that can be disabled by disabling the `moveElement` option.

I am of course open to changing the name of the option or other suggestions you may have. This is just something that is _really_ neccesary to be able to use tether at all in my app.

### CODE REVIEW

**Comment by vanthome** [comment]
Hi,

I have a more critical issue with this behavior. I'm have an Ember.JS components with some containing controls which opens as a tethered element. 
The problem is that I cannot handle the events in the parent component because Ember's event model seem to require that events must origin from an actual DOM child.

I tried to disable the movement as in this PR. Then unfortunately the positioning seems not to be correct in a scrolling container :(

Anyways, I think it's no intuitive to have an option `moveElement` and when set to `false` to still move the element, so this PR should be accepted and/ or merged with `moveElement`.

Greets

**Comment by pzuraq** [comment]
I also support this PR, we are currently using `ember-wormole` which warps the element to another specified container already (typically somewhere near the body in the DOM). For liquid-fire (animation) integration we are going to need to be able to attach the tether to some child of the body rather than to the body itself.

**Comment by Evan-M** [comment]
Looks like the project source code was changed from coffeescript to ec6... thus blocking the pull request?

**Comment by andnp** [comment]
I too am having a similar issue with my app. My use case requires me to make the tethered element a child of another element in the DOM other than body. I wonder if it would be more beneficial to have an optional parameter (newRoot?) that defines where the tethered element is placed. This should be able to handle the Ember.js use cases as well as further abstracting some of the functionality of this library.

**Comment by pzuraq** [comment]
I submitted #96, which updates this PR and bumps the version number. Still haven't gotten a response from HubSpot, hopefully that'll come soon.

**Comment by geekjuice** [comment]
The conversation seems to be continuing in #96, so closing in favor of that PR

**Pull request closed without merging**
