### PR TITLE
Fix positioning bug for disabled gpu optimizations

### PR DESCRIPTION
**Pull request by johgusta**
Issue observed when position of tether element is
set with the css properties top, left, bottom or
right.

Before writing the css to the element's
style their values are parsed to floats, presumably
related to the check against the current css value.
This incorrectly converts '5px' > 5, which is an
illegal css value and is ignored by the browser.

Conversion to float would seem to be incorrect and
is removed.

### CODE REVIEW

**Comment by TrevorBurnham** [comment]
Oof. Confirmed! Thanks for the fix.

**Comment by TrevorBurnham** [comment]
@johgusta Out of curiosity, does this mean that you've found a situation where setting

```js
optimizations: {
  gpu: false
}
```

is necessary?

**Comment by johgusta** [comment]
We're using Drop.js to dynamically display popups and we sometimes experienced issues with blurred text. It would seem to be caused by how webkit handles subpixel antialiasing when rendering on the GPU, http://keithclark.co.uk/articles/gpu-text-rendering-in-webkit/.

**Comment by TrevorBurnham** [comment]
Very interesting. That might be worth mentioning in the documentation.

**Pull request merged**
