### PR TITLE
Allow directional classes to be overridden

### PR DESCRIPTION
**Pull request by rdjpalmer**
This change allows the overriding of *all* classnames, including `side` specific ones, while preserving current behaviour in all other circumstances:

```jsx
new Tether({
  classPrefix: 'example',
  classes: {
    'pinned': 'customPinned',
    'abutted': 'customAbutted',
    'abutted-left': 'customAbuttedLeft',
  }
});

// example class output
.example-element
.customPinned
.customPinned-left
.customAbutted
.customAbuttedLeft
```

This enables tether to be used alongside css modules, where current behaviour of appending `-[side]` to custom classnames conflicts with the "css module way"

### CODE REVIEW

**Comment by k0nserv** [comment]
What's the status of this? We're interested in this getting merged too

cc@TrevorBurnham

**Comment by rdjpalmer** [comment]
@k0nserv seems the project is dead 😕

**Comment by k0nserv** [comment]
It does seem that way yes

**Comment by rdjpalmer** [comment]
Going to close this as it makes me sad to continuously see the PR open in my list

**Pull request closed without merging**
