### PR TITLE
Reposition a center-attached element to left- or right-attached

### PR DESCRIPTION
**Pull request by markalfred**
Opening this PR to discuss the feasibility and desirability of repositioning center-attached elements if they move outside of their constrainer. This originated in a [Drop discussion](https://github.com/HubSpot/drop/issues/16#issuecomment-101299601) but the fix here is in Tether.

Example:

drop

If this is a desirable feature, I'd be happy to update the change in order to make it mergeable :+1:

### CODE REVIEW

**Comment by adamschwartz** [comment]
:+1:

**Comment by geekjuice** [comment]
:beers:

**Comment by NicBright** [comment]
I like this solution as well.

As Tether is no longer CoffeeScript based, the patch just needs some refreshments imho.

**Comment by geekjuice** [comment]
@markalfred Do you mind if I close this PR in favor of https://github.com/HubSpot/tether/compare/horizontal-overflow-fix. This is a great feature we would love to incorporate into Tether and the branch has your changes applied to the new project structure.

**Comment by markalfred** [comment]
:+1: Sorry for falling off the face of the earth. I ran into some problems trying to implement the same functionality on a middle (y) position element and never revisited. The above fix looks great, thanks for this!

**Comment by yairEO** [comment]
whats up with this? is it in or not? I didn't understand @geekjuice 's comment

**Comment by geekjuice** [comment]
I've been busier than expected these past few months and haven't had the bandwidth to fully test these changes and merge them into `master`. As of now, the changes are still only on the branch (which can be pulled down if you need them right away).

My comment was that the changes on this branch were applied before a large project restructuring (when the project still used coffeescript), so there would have been major merge conflicts. The branch I mentioned above ported these changes into the new project format (using ES6).

If you'd like to help get this into `master` sooner, I'd be more than grateful if you'd like to pull down the branch above and help make sure nothing is broken by the changes.

**Comment by yairEO** [comment]
I've updated to the latest version `1.2.0` and used these settings:

    attachment: 'top center'
    targetAttachment: 'middle center'
    constraints: [
        to: 'window'
        attachment: 'together element'
    ] 

And I have this bug, when re-sizing the window (FF 44.0.2 & Chrome 48.0.2564.116 on Win7), the tether element "jumps" (it should be attached to the "star" icon:

gif

**Comment by geekjuice** [comment]
@yairEO do you mind setting up a simple jsbin/fiddle/codepen reproducing the issue and providing the link? Then I'll be happy to take a look.

**Comment by yairEO** [comment]
I'll set it up

**Comment by xandrani** [comment]
An unsubscribe link is needed in these emails. It's a faff on to
unsubscribe on a smartphone.

It's standard practice to do so.

Thanks

**Comment by geekjuice** [comment]
@xandrani There's an unsubscribe link on the right sidebar on the site if you open in a browser. Also that comment doesn't contribute to this thread in any way and should be addressed to GitHub support where it can actually be handled.

**Comment by xandrani** [comment]
Twat

**Comment by xandrani** [comment]
1. I'd have to sign in first. Which is a pain.
2. There's no righthand sidebar
3. Your abrasive attitude is a bad stereotype of programmers of yesteryear.

**Comment by geekjuice** [comment]
@xandrani I'm sorry you feel that my attitude was _abrasive_ when I was just trying to provide some actionable solutions rather than commenting on a thread that really can't do anything about adding an `unsubscribe` button to your email.

> 1. I'd have to sign in first. Which is a pain.
That's fair, but a lot of mobile email clients do have `ignore` and `unsubscribes` baked in so many you should look into one of those clients.

> 2. There's no righthand sidebar
I'll admit I was a bit hasty to mention the righthand sidebar, but I do recall an unsubscribe in the mobile browser. However, there is a righthand sidebar in the browser so _technically_ I'm not wrong to mention it.

> 3. Your abrasive attitude is a bad stereotype of programmers of yesteryear.
See first comment. To be fair, I haven't been in the industry too long so maybe you could set an example of how I _should_ act.

> Twat
See above comment.

**Comment by yairEO** [comment]
There is an unsubscibe button on the bottom of the web version of this page. 
Lets all delete our comments and clean this thread so future developers who might come here won't curse us.

**Comment by geekjuice** [comment]
@yairEO I agree.

**Comment by yairEO** [comment]
I've produces a simple [example page](http://jsbin.com/vitarij/edit?html,css,output):

Try resizing the `output` area

seems like tether goes crazy when the target element has `float:right`. (other properties might also cause this)

**Comment by xandrani** [comment]
I unsubscribed but I'm still getting these emails. GitHub needs to be
renamed ShitHub obviously.

**Pull request closed without merging**
