### PR TITLE
Support multiple scroll parents fixes HubSpot/tether#62

### PR DESCRIPTION
**Pull request by ibash**
I hit the bug where Tether selects the first scrollable parent, HubSpot/tether#62. This naively collects all the scrollable parents and adds event listeners for them.

### CODE REVIEW

**Comment by chrishoage** [comment]
What's the status of this? Kind of sad that this PR went stale, this is a pretty annoying and longstanding bug. 

Is there any chance of it being revived?

**Comment by ibash** [comment]
Probably stale because of changes to the minified / distribution code, which are automated, the actual source changes aren't too complicated.

**Comment by chrishoage** [comment]
Hopefully someone can review your PR soon so it can get merged in!

**Comment by TrevorBurnham** [comment]
@ibash Thanks for this! I've rebased against `master` and merged: https://github.com/HubSpot/tether/commit/b233b197581926d24d0aaa79d8566251ce848d76

**Comment by adamschwartz** [comment]
👍  thx @ibash and @TrevorBurnham!

**Comment by TrevorBurnham** [comment]
Unfortunately this broke code in a couple of places where `scrollParent` instead of `scrollParents` was used. This has been fixed by c1346b6388bfaef7b028f45aeed0d68d58a8aa99 in the latest release, 1.3.1.

**Pull request closed without merging**
