### PR TITLE
Add copyTargetWidth / copyTargetHeight options

### PR DESCRIPTION
**Pull request by arcanis**
This PR implements two new options that allow to force tethered elements to take the same size than the target. It's useful in a large number of use case, such as the one demonstrated by the Select library (https://github.com/HubSpot/select/issues/13).

### CODE REVIEW

**Comment by adamschwartz** [comment]
👍

**Comment by arcanis** [comment]
Ping ?

**Comment by TrevorBurnham** [comment]
I feel like this is beyond the scope of what Tether should do. Tether is for positioning, not styling. If Tether provided a callback at this stage, it would be easy for the user to add this functionality.

**Comment by arcanis** [comment]
I don't quite agree. Positionning is directly related with an object size, as evidenced by the constraint feature. Furthermore, I think there is only few use cases requiring to manually update the tethered element - and because how basic copying the container width/height is, I believe it should be done manually.

WDYT?

**Comment by arcanis** [comment]
ping ? 😃

**Comment by arcanis** [comment]
I've rebased my changes and commited a version increase commit.

**Comment by arcanis** [comment]
<sad cat gif>

**Comment by arcanis** [comment]
Ping @adamschwartz @TrevorBurnham?

**Comment by bdwain** [comment]
@arcanis instead of just copy target width and height, what about being able to specify a percentage of the width and height?

**Comment by arcanis** [comment]
That would be a possibility. However, I don't work on the project who used tether anymore, so I won't be able to test any further change. You can open another PR if you wish to implement a more complex solution.

**Comment by bdwain** [comment]
Ah that's a bummer. Yea it seems like a useful feature and a good PR. Oh well. Thanks for your help and effort.

**Comment by jide** [comment]
Definitely useful, in scope with this module and very simple ! And I need this, too :)

**Comment by arcanis** [comment]
I'm going to go ahead and close this PR to clean my list. Maintainers don't seem willing to merge this anytime soon, despite the clear interest.

**Comment by jide** [comment]
Sad, this was such a trivial PR. As far as im concerned I'll stick to the fork.

**Comment by lolmaus** [comment]
Is this still impossible in upstream? :sob:

**Comment by lolmaus** [comment]
> I feel like this is beyond the scope of what Tether should do. Tether is for positioning, not styling.

Once the tethered element is moved outside its original position, there's no elegant way to assign a width to the element equal to its target. It is plain impossible to do with CSS, and it's extremely frustrating to do with JS due to having to wait for animations, transitions, etc.

Therefore, Tether.js is the only player that can make it right. This PR is simple and efficient.

Please @TrevorBurnham @arcanis, you must advance this. :bow:

**Comment by tsnolan23** [comment]
Agree with @lolmaus 

I just installed the version @arcanis created, and it worked flawlessly. I recommend install his fork if you need this functionality:

`npm install aracanis/tether#patch-1`

**Comment by jide** [comment]
You may want to look at https://popper.js.org, it's similar, with a plugin API.

**Pull request closed without merging**
